use_frameworks!

target 'ShowTime_Example' do
  pod 'ShowTime', :path => '../'

  target 'ShowTime_Tests' do
    inherit! :complete
    pod 'PixelTest', '1.1.0'
  end
end

target 'ShowTimeTodayExtension' do
    pod 'ShowTime', :path => '../'
end
